#+TITLE: OkuCode Readme
#+AUTHOR: OkuCode
#+DESCRIPTION: Information about this colombian geek
#+DATE: <2023-03-16 Thu>

Hello and welcome, this is an interview for my self, so today we have a Oku, and student of systems engineer for about 5 years and a half.


** Hello and welcome, please present to your audience.

Hello everyone, I'm *Juan David Rodas Barco*, JD for short or Oku as my nickname, currently i'm a student of /Systems Engineer and comunications/ from Manizales Unveristy, i live here in Manizales, Caldas for about all my life time.

So currently i'm looking what i like to do in the IT field, but here is an overview of my interest:

1) Backend with rust
2) Dev Ops
3) Linux
4) Rust programming

   
** Tell us about a little more about you.

Since i remember, i'm interest about computers, when i was a kid i like this sentence /i want to be a systems engineer/, but my parents took to seriously, now with about 28 years i still liking all about this amazing world, reading documentation, programming a little, learning how to manipulate data, use linux as my main OS, learning new tools for the job like emacs and more.


** Yeah, you apasonated about tech i know, but what else you do in your free time ???

Well from gaming and read documentation, watch videos on Youtube, most of the time i spend my free time with my beloved ones, my dog *Tommy* and some friends, and looking for something new to learn.


** Then, tell me about your hard skills, you know programming languages and more of that stuff.

As i said earlier i'm learning how to use rust as a backend language, but i have some other skills like:

1) Linux knowledge: As my main OS i'm not only learn the basic commands, also the file system internals, services, software using with it, no gonna lie that was something that bring me passion to learn.
2) Python intermediate: /I hate java/, no get me wrong, this language is awesome, if you like to calls objects everytime, but thanks to python i manage to finish my programming lectures at university
3) Web development basics: It was 2014 when i starting to learn html thanks to dreamweaver CS6, but as i'm looking for new tools to the job more efficiently i learn css, JS was pretty late, when people told me /web is not about to look pretty, is about to make it functional/.
4) Databases: this is something pretty important, data is the new gold of 20 century and that's something i pick quite rencently, right now knowing about relational databases but i don't know about no relational ones
5) Rust programming language: Well this is something funny, when i was doing python for my university lectures, i find this language called rust, and that was one of those things i'm happy about it, thanks to /ferry says/ crate, started in 2018 and now 2023 this is an amazing language i want to work with it in the near future...
6) Git: In my opinion something a must if you are in the tech industry, not only add, commit and push...
7) English Language: My english maybe don't be sophisticated but as my professors and colleges says, this is an important skill, beacuse all the content is made with this language in mind, btw sorry if it is so basic...

   
** Awesome, Do you have project to share with others, i mean something cool to show to other people ??

I want to start with something, i'm not a person who talk with people so much, even in real life i'm always quiet and focus on in own things, so with this in mind, i work in my own stuff primary, but of course, learning rust will eventually bring an interesting projects.

But to show people maybe there's some stuff i do like:

1) [[https://github.com/Oku-Code/void-linux-guide][Void Linux Guide]]
2) An app extension using HTML, CSS and JS
3) Web scrapping using selenium
4) Rust projects from /The book/ and others from /Command line rust/.
5) Dotfiles

   
** What tools do you use in daily basis ??

Here is an overview i don't want to being boring with this:

1) HP 14 laptop: Borrowed from a friend.
2) Dell Optiplex 320: Ancient machine but trust worth it.
3) Void Linux: Stability first and also i don't know how to install debian.
4) Emacs: Could be my os but primary for org and coding sessions

   
** Now, with all of this, what do you want to do in the future ??

To be honest, i don't now, the perception is to have a nice job and live confortably, but here sometimes become a challenge, my goal is keep learning about this amazing world and share with other my experiences in sort of way, but for now i focus on finish my university and then the time will tell what kind of path i should follow...


** So, Do you have social networks or something similar, how people can reach you ??

Social networks, maybe a discord account, but i don't have mainstream social networks like instagram, facebook or twitter, you can send me emails or open an issue here, _i need to fix that eventually_.

#+begin_quote
Thanks to your guest for comming today, and also thanks to the people to take the time and will to read this stuff, really apreciated 
#+end_quote
